theme = "ashen-dev"

[editor]
mouse = false
line-number = "relative"
true-color = true
color-modes = true
continue-comments = false
# bufferline = "multiple"
middle-click-paste = false
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "error"
# Tweaks for the Ashen theme
cursorline = true
# certain diagnostics are styled as curl
undercurl = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spacer", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "register", "file-encoding", "file-type", "spacer", "version-control"]
diagnostics = ["hint", "info", "warning", "error"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.gutters.line-numbers]
min-width = 1

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "hint"
# Minimum severity to show a diagnostic on other lines:
# other-lines = "error"
